# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as a base image
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy the rest of the application code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript application
RUN npm run build

# Use a lightweight Node.js image to run the application
FROM node:20-alpine AS runner

# Set the working directory inside the container
WORKDIR /app

# Copy the build artifacts and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Define environment variables
ENV UNICHAT_MODEL=gpt-4o-mini
ENV UNICHAT_API_KEY=YOUR_OPENAI_API_KEY

# Expose the desired port
EXPOSE 3000

# Run the application
ENTRYPOINT ["node", "build/index.js"]